//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pagos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenesEstados
    {
        public System.Guid OrdenEstadoId { get; set; }
        public string OrdenEstadoEstado { get; set; }
        public Nullable<System.Guid> OrdenId { get; set; }
        public Nullable<System.DateTime> OrdenEstadoFecha { get; set; }
        public Nullable<System.Guid> OrdenEstadoUsuario { get; set; }
        public string OrdenEstadoMotivoRechazo { get; set; }
        public string OrdenEstadoObservaciones { get; set; }
    
        public virtual Ordenes Ordenes { get; set; }
    }
}
