//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pagos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProveedoresDetracciones
    {
        public System.Guid ProveedorDetraccionId { get; set; }
        public System.Guid ProveedorId { get; set; }
        public System.Guid ProveedorDetraccionTipo { get; set; }
        public decimal ProveedorDetraccionPorcentaje { get; set; }
        public string ProveedorDetraccionCuenta { get; set; }
        public Nullable<System.Guid> TipoDetraccionId { get; set; }
    
        public virtual Proveedores Proveedores { get; set; }
        public virtual TiposDetracciones TiposDetracciones { get; set; }
    }
}
