//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pagos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProyectosMontosAprobaciones
    {
        public System.Guid ProyectoMontoAprobacionId { get; set; }
        public Nullable<System.Guid> ProyectoId { get; set; }
        public Nullable<System.Guid> RolId { get; set; }
        public Nullable<decimal> ProyectoMontoAprobacionMaximo { get; set; }
        public Nullable<decimal> ProyectoMontoAprobacionAcumulado { get; set; }
    }
}
