USE [master]
GO

/****** Object:  Database [norton]    Script Date: 06/01/2019 10:37:48 a.m. ******/
CREATE DATABASE [norton]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'norton', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\norton.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'norton_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\norton_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [norton] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [norton].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [norton] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [norton] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [norton] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [norton] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [norton] SET ARITHABORT OFF 
GO

ALTER DATABASE [norton] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [norton] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [norton] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [norton] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [norton] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [norton] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [norton] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [norton] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [norton] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [norton] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [norton] SET  DISABLE_BROKER 
GO

ALTER DATABASE [norton] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [norton] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [norton] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [norton] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [norton] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [norton] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [norton] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [norton] SET RECOVERY FULL 
GO

ALTER DATABASE [norton] SET  MULTI_USER 
GO

ALTER DATABASE [norton] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [norton] SET DB_CHAINING OFF 
GO

ALTER DATABASE [norton] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [norton] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [norton] SET  READ_WRITE 
GO


